from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from .provider_presets import (
    provider_presets_payload,
    resolve_provider_preset,
)
from .state import atomic_write_text


PROFILE_NAME_RE = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9_.-]{0,62}[A-Za-z0-9])?\Z")
WINDOWS_RESERVED_PROFILE_NAMES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
}
PROVIDER_ID_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]*")
ENV_KEY_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
RESERVED_PROVIDER_IDS = {"openai", "ollama", "lmstudio"}


def codex_home(path: str | os.PathLike[str] | None = None) -> Path:
    if path:
        return Path(path).expanduser().resolve()
    configured = os.environ.get("CODEX_HOME")
    if configured:
        return Path(configured).expanduser().resolve()
    return (Path.home() / ".codex").resolve()


def longcat_profile_text() -> str:
    return provider_preset_profile_text("longcat-2.0")


def _toml_string(value: str) -> str:
    """JSON strings are valid TOML basic strings and escape controls safely."""

    return json.dumps(value, ensure_ascii=False)


def is_valid_profile_name(value: Any) -> bool:
    return (
        isinstance(value, str)
        and PROFILE_NAME_RE.fullmatch(value) is not None
        and value.split(".", 1)[0].upper() not in WINDOWS_RESERVED_PROFILE_NAMES
    )


def validate_profile_name(value: str) -> str:
    if not is_valid_profile_name(value):
        raise SystemExit(
            "profile name must be 1-64 characters, start and end with a letter or number, "
            "contain only letters, numbers, dots, hyphens, and underscores, and not be a "
            "reserved Windows device name"
        )
    return value


def validate_provider_id(value: str) -> str:
    if not PROVIDER_ID_RE.fullmatch(value):
        raise SystemExit("provider id must start with a letter and contain only letters, numbers, hyphens, and underscores")
    if value.lower() in RESERVED_PROVIDER_IDS:
        raise SystemExit(f"custom provider id is reserved by Codex: {value}")
    return value


def validate_base_url(value: str) -> str:
    parsed = urlsplit(value)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise SystemExit("base URL must be an absolute http(s) URL")
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise SystemExit("base URL must not contain credentials, a query string, or a fragment")
    return value.rstrip("/")


def provider_profile_text(
    *,
    provider_id: str,
    display_name: str,
    base_url: str,
    model: str,
    env_key: str,
    wire_api: str | None = None,
    reasoning_effort: str | None = None,
) -> str:
    provider_id = validate_provider_id(provider_id)
    base_url = validate_base_url(base_url)
    if not display_name.strip() or any(ord(char) < 32 for char in display_name):
        raise SystemExit("display name must be non-empty and contain no control characters")
    if not model.strip() or any(ord(char) < 32 for char in model):
        raise SystemExit("model must be non-empty and contain no control characters")
    if not ENV_KEY_RE.fullmatch(env_key):
        raise SystemExit("env key must be a valid environment variable name")
    if wire_api and wire_api != "responses":
        raise SystemExit(
            "current Codex workers require wire API 'responses'; use a reviewed "
            "gateway for Chat Completions-only providers"
        )
    if reasoning_effort and reasoning_effort not in {"minimal", "low", "medium", "high", "xhigh"}:
        raise SystemExit("reasoning effort must be one of minimal, low, medium, high, or xhigh")
    lines = [
        f"# Generated by CostMarshal. Keep {env_key} outside this file.",
        f"model_provider = {_toml_string(provider_id)}",
        f"model = {_toml_string(model)}",
    ]
    if reasoning_effort:
        lines.append(f"model_reasoning_effort = {_toml_string(reasoning_effort)}")
    lines.extend(
        [
            "disable_response_storage = true",
            'web_search = "disabled"',
            "",
            f"[model_providers.{provider_id}]",
            f"name = {_toml_string(display_name)}",
            f"base_url = {_toml_string(base_url)}",
        ]
    )
    if wire_api:
        lines.append(f"wire_api = {_toml_string(wire_api)}")
    lines.extend([f"env_key = {_toml_string(env_key)}", ""])
    return "\n".join(lines)


def provider_preset_profile_text(
    preset_id: str,
    *,
    model: str | None = None,
    reasoning_effort: str | None = None,
) -> str:
    try:
        preset = resolve_provider_preset(preset_id)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    if preset.wire_api != "responses":
        raise SystemExit(
            f"{preset.preset_id} is not directly compatible with the current "
            "Responses-only Codex worker; use a reviewed Responses gateway "
            "and configure that gateway as a custom provider"
        )
    return provider_profile_text(
        provider_id=preset.provider_id,
        display_name=preset.display_name,
        base_url=preset.base_url,
        model=model or preset.default_model,
        env_key=preset.env_key,
        wire_api=preset.wire_api,
        reasoning_effort=reasoning_effort or preset.reasoning_effort,
    )


def write_profile(*, home: Path, profile: str, text: str, force: bool, dry_run: bool) -> dict[str, Any]:
    profile = validate_profile_name(profile)
    path = home / f"{profile}.config.toml"
    if path.exists() and not force:
        raise SystemExit(f"Profile already exists; use --force to replace it: {path}")
    payload = {"status": "ok", "dry_run": bool(dry_run), "profile": profile, "path": str(path)}
    if not dry_run:
        home.mkdir(parents=True, exist_ok=True)
        atomic_write_text(path, text)
    return payload


def command_configure_profiles(args: Any) -> None:
    home = codex_home(args.codex_home)
    payload = write_profile(
        home=home,
        profile=str(args.longcat_profile or "longcat"),
        text=longcat_profile_text(),
        force=bool(args.force),
        dry_run=bool(args.dry_run),
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def command_configure_provider(args: Any) -> None:
    preset_name = str(getattr(args, "preset", None) or "").strip()
    if preset_name:
        custom_fields = {
            "--provider-id": getattr(args, "provider_id", None),
            "--display-name": getattr(args, "display_name", None),
            "--base-url": getattr(args, "base_url", None),
            "--env-key": getattr(args, "env_key", None),
            "--wire-api": getattr(args, "wire_api", None),
        }
        conflicts = [name for name, value in custom_fields.items() if value is not None]
        if conflicts:
            raise SystemExit(
                "--preset cannot be combined with connection overrides: "
                + ", ".join(conflicts)
            )
        try:
            preset = resolve_provider_preset(preset_name)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
        profile = str(getattr(args, "profile", None) or preset.provider_id)
        model = str(getattr(args, "model", None) or preset.default_model)
        text = provider_preset_profile_text(
            preset.preset_id,
            model=model,
            reasoning_effort=(
                str(args.reasoning_effort) if args.reasoning_effort else None
            ),
        )
        provider_id = preset.provider_id
        env_key = preset.env_key
    else:
        required = {
            "--profile": getattr(args, "profile", None),
            "--provider-id": getattr(args, "provider_id", None),
            "--base-url": getattr(args, "base_url", None),
            "--model": getattr(args, "model", None),
            "--env-key": getattr(args, "env_key", None),
        }
        missing = [name for name, value in required.items() if not value]
        if missing:
            raise SystemExit(
                "custom provider configuration requires: " + ", ".join(missing)
            )
        profile = str(args.profile)
        model = str(args.model)
        provider_id = str(args.provider_id)
        env_key = str(args.env_key)
        text = provider_profile_text(
            provider_id=provider_id,
            display_name=str(args.display_name or args.provider_id),
            base_url=str(args.base_url),
            model=model,
            env_key=env_key,
            wire_api=str(args.wire_api) if args.wire_api else None,
            reasoning_effort=str(args.reasoning_effort) if args.reasoning_effort else None,
        )
    payload = write_profile(
        home=codex_home(args.codex_home),
        profile=profile,
        text=text,
        force=bool(args.force),
        dry_run=bool(args.dry_run),
    )
    payload["provider_id"] = provider_id
    payload["model"] = model
    payload["env_key"] = env_key
    if preset_name:
        payload["preset"] = preset.preset_id
        payload["capabilities"] = {
            "api": list(preset.api_capabilities),
            "effective": list(preset.effective_capabilities),
            "runtime_unavailable": list(preset.unavailable_runtime_capabilities),
        }
        payload["catalog_provider"] = preset.catalog_provider(
            tier=str(getattr(args, "tier", None) or "medium"),
            profile=profile,
            model=model,
        )
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def command_provider_presets(args: Any) -> None:
    try:
        payload = provider_presets_payload(getattr(args, "preset", None))
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    print(json.dumps(payload, ensure_ascii=False, indent=2))
