from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from .state import atomic_write_text


def codex_home(path: str | None = None) -> Path:
    if path:
        return Path(path).expanduser().resolve()
    configured = os.environ.get("CODEX_HOME")
    if configured:
        return Path(configured).expanduser().resolve()
    return (Path.home() / ".codex").resolve()


def longcat_profile_text() -> str:
    return """# Generated by CostMarshal. Keep LONGCAT_API_KEY outside this file.
model_provider = "longcat"
model = "LongCat-2.0"
model_reasoning_effort = "low"
disable_response_storage = true
web_search = "disabled"

[model_providers.longcat]
name = "LongCat"
base_url = "https://api.longcat.chat/openai/v1"
wire_api = "responses"
env_key = "LONGCAT_API_KEY"
"""


def command_configure_profiles(args: Any) -> None:
    profile = str(args.longcat_profile or "longcat")
    if not re.fullmatch(r"[A-Za-z0-9_-]+", profile):
        raise SystemExit("profile name may contain only letters, numbers, hyphens, and underscores")
    home = codex_home(args.codex_home)
    path = home / f"{profile}.config.toml"
    if path.exists() and not args.force:
        raise SystemExit(f"Profile already exists; use --force to replace it: {path}")
    payload = {"status": "ok", "dry_run": bool(args.dry_run), "profile": profile, "path": str(path)}
    if not args.dry_run:
        home.mkdir(parents=True, exist_ok=True)
        atomic_write_text(path, longcat_profile_text())
    print(json.dumps(payload, ensure_ascii=False, indent=2))
